name: Deploy to huggingface

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight
  workflow_dispatch: # Manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create temporary repository with data, README and LICENSE
        run: |
          mkdir -p /tmp/data_repo
          cp -r data/* /tmp/data_repo/
          cp README.md /tmp/data_repo/
          cp LICENSE /tmp/data_repo/
          cd /tmp/data_repo
          git init
          git add .
          git commit -m "Push data, README and LICENSE to Hugging Face"
          git branch -M main  # Rename the current branch to main

      - name: Push to Hugging Face
        working-directory: /tmp/data_repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/datasets/Tunisian_reddit
          echo -e "machine huggingface.co\nlogin api\npassword $HF_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git push -f hf main
